// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llzgejuvmfpchccqavyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsemdlanV2bWZwY2hjY3FhdnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODQxMjAsImV4cCI6MjA2NzU2MDEyMH0.auzCIB1lWLkHaA42Sxh0iI42ylVa-fhWtdh4R82KSms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});